### PR TITLE
support java 1.5+

### PR DESCRIPTION
**Pull request by qxo**

### CODE REVIEW

**Comment by isaki-x** [comment]
This is arguable a step in the wrong direction. If anything, Kryo should drop support for Java 7. Guava already only builds for 1.8 for example (look at their master pom).

If Kryo really wants to support legacy, unsupported Java versions then I ask that they do what bouncy castle and other frameworks have done and provide a standard build on the oldest supported Java (Java 8) and a legacy build for compatibility with older Java versions. There is no reason to pay the performance and feature cost associated with supporting old, unsupported JVMs for every application that utilizes Kryo when up until this point every JVM using it has been at least Java 7.

Perhaps the right answer is to update the 3.X series to be compatible with 1.5, the 4.X series should remain compatible with 7, and the new 5.X series should support only the oldest supported JVM (Java 8). This will also have the benefit of allowing Kryo to use new language features in its code base.

**Comment by magro** [comment]
I'd agree @isaki-x

Also related: #500

**Comment by qxo** [comment]
ok ,It'll change javaTarget default to 1.7 , leave choice for the library publisher

**Comment by NathanSweet** [comment]
If it doesn't hurt Kryo to support older Java versions, we should do so. I don't believe there is any performance cost with generating bytecodes compatible with older versions of Java. That leaves only the benefit of using newer language features in the Kryo codebase, which is not terribly important for us. If we can easily support newer Java version features, such as how we serialize lamdas, without losing support for older versions of Java, that is good.

FWIW, I personally have Java 7 projects using Kryo which won't be updating to a newer Java any time soon for various reasons.

**Comment by isaki-x** [comment]
This PR is now effectively a no-op. Placing the version in a property isn't a bad idea. However, I tend to avoid using properties without prefixes. It is up to the Kryo owners, but I would probably name the property something like ```kryo.javaTarget```.

**Pull request merged**
