### PR TITLE
Added UnmodifiableCollectionsSerializer to default config and added simp...

### PR DESCRIPTION
**Pull request by megglos**
https://github.com/EsotericSoftware/kryo/issues/151#

### CODE REVIEW

**Comment by magro** [comment]
@NathanSweet WDYT?

**Comment by NathanSweet** [comment]
I don't think JVM specific serializers should be registered by default. I guess including them is fine as long as it is documented.

**Comment by magro** [comment]
Sounds reasonable. For jvm specific serializers the jdk compatibility should also be documented. kryo-serializers are built with jdk6-8 (openjdk/oracle) and ibm-jdk-7 (see https://jenkins.inoio.de/view/kryo/).

**Comment by thomasdarimont** [comment]
Would be great to have that - whats the state of this PR?

**Comment by groundhog2k** [comment]
@megglos Great PR!

**Pull request closed without merging**
