### PR TITLE
Use recommended sort order for modifiers

### PR DESCRIPTION
**Pull request by theigl**
Addresses the second code style issue described in #739 by applying Java's recommended modifier order.

See https://stackoverflow.com/a/16732059/441266

### CODE REVIEW

**Comment by magro** [comment]
@theigl I like that! 🙂 Unfortunately there are now conflicts due to the previous PRs/merges... 😕

**Comment by theigl** [comment]
@magro: Thanks! I just resolved the conflicts.

**Comment by magro** [comment]
@theigl after some issues with publishing I now managed to push RC7 - on its way to maven central...

**Comment by theigl** [comment]
@magro: It seems the release didn't make it to Maven Central. 👀

**Pull request merged**
