### PR TITLE
Add resolve GenericArrayType in GenericsUtil#resolveTypeVariable()

### LINKED ISSUE #655: Unable to resolve type variable
Using Kryo 5.0.0-RC3-SNAPSHOT, I get the following Stacktrace when running the test:

```
om.esotericsoftware.kryo.KryoException: Unable to resolve type variable: T

	at com.esotericsoftware.kryo.util.GenericsUtil.resolveTypeVariable(GenericsUtil.java:112)
	at com.esotericsoftware.kryo.util.GenericsUtil.resolveType(GenericsUtil.java:41)
	at com.esotericsoftware.kryo.util.Generics$GenericType.initialize(Generics.java:294)
	at com.esotericsoftware.kryo.util.Generics$GenericType.<init>(Generics.java:259)
	at com.esotericsoftware.kryo.serializers.CachedFields.addField(CachedFields.java:139)
	at com.esotericsoftware.kryo.serializers.CachedFields.rebuild(CachedFields.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:82)
	at com.esotericsoftware.kryo.SerializerFactory$FieldSerializerFactory.newSerializer(SerializerFactory.java:124)
	at com.esotericsoftware.kryo.SerializerFactory$FieldSerializerFactory.newSerializer(SerializerFactory.java:108)
	at com.esotericsoftware.kryo.Kryo.newDefaultSerializer(Kryo.java:395)
	at com.esotericsoftware.kryo.Kryo.getDefaultSerializer(Kryo.java:380)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.registerImplicit(DefaultClassResolver.java:87)
	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:500)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:110)
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:532)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:627)
```

```
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Output;
import org.junit.jupiter.api.Test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

import static org.assertj.core.api.Assertions.assertThat;

public class SerializeTest {

	@Test
	void serializeClassList() {
		final Kryo kryo = new Kryo();
		kryo.setRegistrationRequired(false);

		final Output output = new Output(1024);
		kryo.writeClassAndObject(output, new LoadableClassList(new ArrayList<>()));
		final byte[] result = output.toBytes();

		assertThat(result).isNotNull();
	}

	static class LoadableClassList extends Loadable<Class<?>[]> {

		private final List<Class<?>> groups;

		LoadableClassList(List<Class<?>> groups) {
			this.groups = groups;
		}

		@Override
		protected Class<?>[] load() {
			return groups.toArray(new Class<?>[]{});
		}
	}

	abstract static class Loadable<T> implements Supplier<T>, Serializable {

		private transient T t;

		@Override
		public T get() {
			if (t == null) {
				t = load();
			}
			return t;
		}

		protected abstract T load();
	}
}
```

Related to #622

### PR DESCRIPTION
**Pull request by maxisvest**
Try to fix #655 problem, seems like missing an option with `GenericArrayType`

### CODE REVIEW

**Comment by theigl** [comment]
@maxisvest: Was there any issues with your fix or did you close the PR because it didn't get merged for quite a while?

**Comment by maxisvest** [comment]
> @maxisvest: Was there any issues with your fix or did you close the PR because it didn't get merged for quite a while?

No, I'm not sure this change will be safe to merge. Does my PR fix your problem?

**Comment by theigl** [comment]
@maxisvest: It fixes my problem but there are even more complicated cases as shown in #707. I'm currently collecting and simplifying all existing test-cases and I'm trying to review existing attempts at fixes or workarounds.

**Comment by maxisvest** [comment]
@theigl ,Sorry I can't offer you any cases about it. Actually I merge #683 to my branch to disable kryo generic optimization capablility. I decide sacrifice some performance to ensure serialization successfully complete.

**Pull request closed without merging**
