### PR TITLE
Fix positioning 

### PR DESCRIPTION
**Pull request by stau**
Fix positioning and setting of byteOrder on setting buffer + tests

The tests for the ByteBufferInput are aimed for externally given buffers.

### CODE REVIEW

**Comment by magro** [comment]
The code looks good to me. The commit message has as first line "- ByteBufferInput", which is not that useful in a list of commits, can you use s.th. more meaningful? Thanks!

**Comment by stau** [comment]
Thanks for the review, I've changed the first line of the commit into something more meaningful.

**Comment by magro** [comment]
Thanks @stau! @romix LGTM, do you want to have a look at it as well, as you know this IO stuff better? Otherwise I'd merge it.

**Comment by romix** [comment]
LGTM.

**Pull request merged**
