### PR TITLE
Add a unit test for a Kotlin lambda class.

### PR DESCRIPTION
**Pull request by chrisr3**
This _appears_ to be enough to include a Kotlin JUnit case, although IntelliJ doesn't like it much :nauseated_face:.

### CODE REVIEW

**Comment by theigl** [comment]
I just pushed another solution to this: #949. 

Could you check if that works better for you in IntelliJ? For me it works quite well after running a Maven re-import.

**Comment by chrisr3** [comment]
> Could you check if that works better for you in IntelliJ? For me it works quite well after running a Maven re-import.

IntelliJ seems to like this solution better than mine, although I'm still struggling to persuade it to execute the new test. However, I'm more accustomed to using IntelliJ with Gradle projects rather than Maven ones, so all my problems could _still_ be down to "user error"... :facepalm:.

**Comment by theigl** [comment]
> IntelliJ seems to like this solution better than mine, although I'm still struggling to persuade it to execute the new test. However, I'm more accustomed to using IntelliJ with Gradle projects rather than Maven ones, so all my problems could still be down to "user error"... 🤦.

Thanks a lot for testing it! Running the test works for me, but I'll try once more with a newly imported project just to make sure.

**Comment by theigl** [comment]
We went with a different implementation in https://github.com/EsotericSoftware/kryo/pull/949

**Pull request closed without merging**
