### PR TITLE
remove intermediate byte[] and change visibility to enable override

### PR DESCRIPTION
**Pull request by guoguanglei**
1. remove intermediate byte[] to avoid garbage in ByteBufferOutput
2. change visibility to enable override in Input

### CODE REVIEW

**Comment by isaki-x** [comment]
I can't comment on the visibility change; I leave that to the repo owners.

However.

This change is a performance decrease; the cost of allocating a pointer on the stack to the backing array of the buffer will be cheaper than invoking methods to access the same data. Using the raw array is the better option. While using the method based access may look nicer, for a library like Kryo where performance is key such convinces are unwarranted.

Calling methods in your for loop declaration is even worse. Take this simple example:

```java
import org.junit.Test;

public class FooTest {
    
    @Test
    public void testLoop() {
        final TestLoopHelper value = new TestLoopHelper(10);
        for (int i = 0; i < value.get(); ++i) {
            System.out.println("Current loop value: " + Integer.toString(i));
        }
    }

    private static final class TestLoopHelper {
        
        private final int x;
        private int counter;
        
        TestLoopHelper(final int x) {
            super();
            this.x = x;
            this.counter = 0;
        }
        
        public int get() {
            System.out.println("Hello world: " + Integer.toString(++this.counter));
            return this.x;
        }
    }  
}
```

The method in loop gets called 11 times for a 10 iteration loop!

```
Hello world: 1
Current loop value: 0
Hello world: 2
Current loop value: 1
Hello world: 3
Current loop value: 2
Hello world: 4
Current loop value: 3
Hello world: 5
Current loop value: 4
Hello world: 6
Current loop value: 5
Hello world: 7
Current loop value: 6
Hello world: 8
Current loop value: 7
Hello world: 9
Current loop value: 8
Hello world: 10
Current loop value: 9
Hello world: 11
```

**Comment by isaki-x** [comment]
@magro I use Kryo for its performance; I'm always watching the PRs and commits to make sure nothing is going to impact my very tight performance constraints.

**Comment by magro** [comment]
@isaki-x awesome! :-)

**Comment by NathanSweet** [comment]
String `getBytes` should generally be avoided. We avoid it in Output so makes sense to do the same in ByteBufferOutput.

ByteBufferInput `optional` is intended to be private API. What reason would there be for overriding it? You are supposed to override `fill` instead.

**Comment by isaki-x** [comment]
@NathanSweet 

This implementation has introduced a bug/compatibility issue. You are casting a char to a byte, which is invalid in Java due to unicode (such as UTF-8) as a character can be more than one byte.

Also, calling charAt() does incur a bounds check on every invocation, so it might be worth benchmarking to see if this route is actually worth avoiding the extra byte[] allocation.

Finally, if you are going to be unicode compatible (which you were, and no longer are, so that's a breaking change) you will end up allocating a new byte[] for every char when you decode the unicode into raw bytes (or have complex code to do the decoding directly instead of using built in classes), so the old way of doing things was probably the best way all things considered.

Thanks!

**Comment by NathanSweet** [comment]
@isaki-x Casting to byte is valid because in this code path every character in the string is guaranteed to be ASCII. I didn't benchmark this change, but String writing was benchmarked for Output `writeString`, which does the same.

**Comment by isaki-x** [comment]
Sweet (no pun intended). Thanks for the info.

**Pull request closed without merging**
