### PR TITLE
Fix EsotericSoftware/kryo#548

### PR DESCRIPTION
**Pull request by alexandrebouchard**
Change behaviour of the singleton serializers: contents of the singletons no longer considered immutable.

### CODE REVIEW

**Comment by magro** [comment]
Thanks! To prevent regressions it would be awesome to have a test for this.

**Comment by alexandrebouchard** [comment]
My pleasure. Just added test cases.

**Comment by magro** [comment]
Thanks! Can you please squash the commits? Then I will merge.

**Comment by magro** [comment]
Thanks! You could also push -f btw.

**Comment by magro** [comment]
Closed with #576

**Pull request closed without merging**
