### PR TITLE
[BugFix] Reset the serializer generics when returning a previously read object

### PR DESCRIPTION
**Pull request by jlmorton**
This pull request fixes the bug described in issue: https://github.com/EsotericSoftware/kryo/issues/384

### CODE REVIEW

**Comment by magro** [comment]
@jmorton Can you add the test from the issue to the commit?

@romix WDYT?

**Comment by magro** [comment]
@jmorton Does this fix #377 as well?

**Comment by jlmorton** [comment]
Thanks, I've added the test to this pull request.  I wasn't quite sure where it best fit, but I added it to MapSerializerTest.

I did notice #377 before I opened #384.  Interestingly, this change did in fact fix #377 in 3.0.1, which is the version we are currently using.  However, it did not fix it in master.  I've spent some time investigating #377 and I think I see an additional issue in master that is breaking #384.  I don't have a fix at the moment, but I'll post some thoughts on that thread.

**Comment by magro** [comment]
@romix Can you have a look at this one and #377? Otherwise I'd have to understand FieldSerializer/Generics details which would take some time (and not sure when I could start looking at this).

**Comment by romix** [comment]
@magro I'll try to have a look. But I'm very busy at work recently. And this kind of bugs is usually very subtle and requires quite some attention and time to be analysed and fixed properly. So, I promise to have a look, but I don't promise it will happen very soon ;-)

**Comment by magro** [comment]
@romix Ok :-)

**Comment by magro** [comment]
Resolved by #433

**Pull request closed without merging**
